[project]
name = "blog-writer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "httpx>=0.27.0",
    "asyncpg>=0.29.0",
    "feedparser>=6.0.11",
]
