"""
This type stub file was generated by pyright.
"""

def guarded(meth): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """A decorator to add a sanity check to ConnectionResource methods."""
    ...

class ConnectionResource:
    __slots__ = ...
    def __init__(self, connection) -> None:
        ...
    


