"""
This type stub file was generated by pyright.
"""

import typing
from .types import ServerVersion

version_regex: typing.Final = ...
class _VersionDict(typing.TypedDict):
    major: int
    minor: int | None
    micro: int | None
    releaselevel: str | None
    serial: int | None
    ...


def split_server_version_string(version_string: str) -> ServerVersion:
    ...

